import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// Set consistent metadata to avoid hydration mismatches
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Add suppressHydrationWarning to body to handle potential mismatches */}
      <body suppressHydrationWarning={true} className="bg-black">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
